name: CI

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: Global tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test tic tac toe
        run: cargo test
